package com.mercury.auth.exception;

public interface ErrorCodes {
    String USER_NOT_FOUND = "USER_NOT_FOUND";
    String TENANT_NOT_FOUND = "TENANT_NOT_FOUND";
    String USER_DISABLED = "USER_DISABLED";
    String BAD_CREDENTIALS = "BAD_CREDENTIALS";
    String DUPLICATE_USERNAME = "DUPLICATE_USERNAME";
    String DUPLICATE_TENANT = "DUPLICATE_TENANT";
    String DUPLICATE_EMAIL = "DUPLICATE_EMAIL";
    String DUPLICATE_PHONE = "DUPLICATE_PHONE";
    String PASSWORD_MISMATCH = "PASSWORD_MISMATCH";
    String INVALID_CODE = "INVALID_CODE";
    String CAPTCHA_REQUIRED = "CAPTCHA_REQUIRED";
    String RATE_LIMITED = "RATE_LIMITED";
    String INVALID_TOKEN = "INVALID_TOKEN";
    String TOKEN_BLACKLISTED = "TOKEN_BLACKLISTED";
    String TENANT_MISMATCH = "TENANT_MISMATCH";
    String TENANT_DISABLED = "TENANT_DISABLED";
    String VALIDATION_FAILED = "VALIDATION_FAILED";
    String INTERNAL_ERROR = "INTERNAL_ERROR";
}
