package com.mercury.auth.exception;

public enum ErrorCodes {
    USER_NOT_FOUND("USER_NOT_FOUND", "USER_NOT_FOUND"),
    TENANT_NOT_FOUND("TENANT_NOT_FOUND", "TENANT_NOT_FOUND"),
    USER_DISABLED("USER_DISABLED", "USER_DISABLED"),
    BAD_CREDENTIALS("BAD_CREDENTIALS", "BAD_CREDENTIALS"),
    DUPLICATE_USERNAME("DUPLICATE_USERNAME", "DUPLICATE_USERNAME"),
    DUPLICATE_TENANT("DUPLICATE_TENANT", "DUPLICATE_TENANT"),
    DUPLICATE_EMAIL("DUPLICATE_EMAIL", "DUPLICATE_EMAIL"),
    DUPLICATE_PHONE("DUPLICATE_PHONE", "DUPLICATE_PHONE"),
    PASSWORD_MISMATCH("PASSWORD_MISMATCH", "PASSWORD_MISMATCH"),
    INVALID_CODE("INVALID_CODE", "INVALID_CODE"),
    CAPTCHA_REQUIRED("CAPTCHA_REQUIRED", "CAPTCHA_REQUIRED"),
    RATE_LIMITED("RATE_LIMITED", "RATE_LIMITED"),
    INVALID_TOKEN("INVALID_TOKEN", "INVALID_TOKEN"),
    TOKEN_BLACKLISTED("TOKEN_BLACKLISTED", "TOKEN_BLACKLISTED"),
    TENANT_MISMATCH("TENANT_MISMATCH", "TENANT_MISMATCH"),
    TENANT_DISABLED("TENANT_DISABLED", "TENANT_DISABLED"),
    VALIDATION_FAILED("VALIDATION_FAILED", "VALIDATION_FAILED"),
    INTERNAL_ERROR("INTERNAL_ERROR", "INTERNAL_ERROR");

    private final String code;
    private final String message;

    ErrorCodes(String code, String message) {
        this.code = code;
        this.message = message;
    }

    public String getCode() {
        return code;
    }

    public String getMessage() {
        return message;
    }
}
