package com.mercury.auth.dto;

public enum AuthAction {
    REGISTER_PASSWORD,
    REGISTER_EMAIL,
    LOGIN_PASSWORD,
    LOGIN_EMAIL,
    SEND_EMAIL_CODE,
    SEND_PHONE_CODE,
    REGISTER_PHONE,
    LOGIN_PHONE,
    LOGIN_WECHAT,
    VERIFY_TOKEN,
    REFRESH_TOKEN,
    LOGOUT,
    UPDATE_USER_STATUS,
    CHANGE_PASSWORD,
    TOKEN_USER_LOOKUP,
    TOKEN_USER_DISABLED
}
